config/routes.rb
# frozen_string_literal: true
Samson::Application.routes.draw do
  root to: 'projects#index'

  namespace :api do
    resources :deploys, only: [:index, :show] do
      collection do
        get :active_count
      end
    end

    resources :deploy_groups, only: [:index]

    resources :projects, only: [:index] do
      resources :automated_deploys, only: [:create]
      resources :builds, only: [:create]
      resources :deploys, only: [:index]
      resources :stages, only: [:index] do
        member do
          get :deploy_groups, to: 'deploy_groups#index'
        end
      end
    end

    resources :stages, only: [] do
      resources :deploys, only: [:index]
      post :clone, to: 'stages#clone'
    end

    resources :locks, only: [:index, :create, :destroy]
    delete '/locks', to: 'locks#destroy_via_resource'

    resources :users, only: [:destroy]
  end

  resources :projects, except: [:destroy] do
    resources :jobs, only: [:index, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :builds, only: [:show, :index, :new, :create, :edit, :update] do
      member do
        post :build_docker_image
      end
    end

    resource :build_command, only: [:show, :update]

    resources :deploys, only: [:index, :show, :destroy] do
      collection do
        get :active
      end

      member do
        post :buddy_check
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create], id: Release::ROUTE_REGEX

    resources :stages do
      collection do
        patch :reorder
      end

      member do
        get :clone, to: 'stages#clone'
      end

      resources :deploys, only: [:new, :create] do
        collection do
          post :confirm
        end
      end

      resource :commit_statuses, only: [:show]
    end

    resource :changelog, only: [:show]
    resource :stars, only: [:create]
    resources :webhooks, only: [:index, :create, :destroy]
    resources :outbound_webhooks, only: [:create, :destroy]
    resources :references, only: [:index]
    resources :users, only: [:index, :update]

    member do
      get :deploy_group_versions
    end
  end

  resources :project_roles, only: [:create]
  resources :streams, only: [:show]
  resources :locks, only: [:create, :destroy]

  resources :deploys, only: [:index] do
    collection do
      get :active
      get :search
    end
  end

  resources :deploy_groups, only: [:show]

  resource :profile, only: [:show, :update]

  resources :access_tokens, only: [:index, :new, :create, :destroy]

  resources :versions, only: [:index]

  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  post '/auth/ldap/callback', to: 'sessions#ldap'
  get '/auth/gitlab/callback', to: 'sessions#gitlab'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :csv_exports, only: [:index, :new, :create, :show]
  resources :dashboards, only: [:show] do
    member do
      get :deploy_groups
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy] do
      resource :user_merges, only: [:new, :create]
    end
    resources :projects, only: [:index, :destroy]
    resources :commands, except: [:edit]
    resources :secrets, except: [:edit]
    resources :vault_servers, except: [:edit] do
      member do
        post :sync
      end
    end
    resources :environments, except: [:edit]
    resources :deploy_groups do
      member do
        post :deploy_all
        get :create_all_stages_preview
        post :create_all_stages
        post :merge_all_stages
        post :delete_all_stages
      end
    end
  end

  namespace :integrations do
    post "/circleci/:token" => "circleci#create", as: :circleci_deploy
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/buildkite/:token" => "buildkite#create", as: :buildkite_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  resources :access_requests, only: [:new, :create]

  mount SseRailsEngine::Engine, at: '/streaming'

  use_doorkeeper # adds oauth/* routes
  resources :oauth_test, only: [:index, :show] if %w[development test].include?(Rails.env)
end

app/views/shared/_alerts.html.erb
<% flash_messages.each do |type, klass, message| %>
  <div class="alert alert-<%= klass %>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= message %>
    <%= link_to_request_access if display_access_request_link?(type) %>
  </div>
<% end %>

<!-- Flash messages for ajax requests -->
<mc-messages></mc-messages>

app/views/shared/_dashboard.html.erb
<% if resource.dashboard.present? %>
  <h2>Dashboard</h2>
  <div><%= sanitize resource.dashboard, tags: Loofah::HTML5::WhiteList::ACCEPTABLE_ELEMENTS + %w[iframe] %></div>
<% end %>

app/views/shared/_dashboard_field.html.erb
<fieldset>
  <legend>
    Dashboard
    <%= additional_info "HTML that should be displayed on the show page. No Javascript allowed." %>
  </legend>
  <%= form.text_area :dashboard, class: "form-control", rows: 4 %>
</fieldset>

app/views/shared/_deploys_table.html.erb
<section class="tabs">
  <table class="table">
    <thead>
      <tr>
        <% unless @project %>
          <th>Project</th>
        <% end %>

        <th>When</th>
        <th>Who</th>
        <% unless @stage %>
          <th>Stage</th>
        <% end %>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render partial: "/projects/deploy", collection: @deploys %>
    </tbody>
  </table>

  <%= paginate @deploys if @deploys.respond_to?(:total_pages) %>
</section>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-lg-5 col-lg-offset-1 alert alert-warning">
      <p><strong>Ooops!</strong> There was an error:</p>
      <%= render_nested_errors(object) %>
    </div>
  </div>
<% end %>

app/views/shared/_github_link.html.erb
<%= link_to project.repository_homepage, class: "github", target: "_blank", title: "View repository on GitHub" do %>
  <i class="fa fa-github"></i>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "Samson", root_path, class: "navbar-brand" %>

    <ul class="nav navbar-nav">
      <% if current_user %>
        <li class="dropdown <%= 'active' if request.path.starts_with?('/projects') %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" focus-on="{ click: '#project_search' }">Projects <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <a class="padding-sm">
                <input id="project_search" type="search" handle-dropdown-selection class="filter-list form-control input-block" placeholder="Search projects" data-target=".filtered-projects">
              </a>
            </li>
            <li class="divider"></li>
            <% Project.ordered_for_user(current_user).each do |project| %>
              <li class="filtered-projects">
                <%= link_to project do %>
                  <% starred = current_user.starred_project?(project) %>
                  <span class="glyphicon <%= 'glyphicon-star' if starred %>">
                    <%= '&nbsp;'.html_safe unless starred %>
                  </span>
                  <%= project.name %>
                <% end %>
              </li>
            <% end %>
            <% if current_user.admin? %>
              <li class="divider"></li>
              <li><%= link_to "Manage", admin_projects_path %></li>
            <% end %>
          </ul>
        </li>
        <% if DeployGroup.enabled? %>
          <li class="dropdown <%= 'active' if request.path.starts_with?('/dashboards') %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Environments <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% environments.each do |env| %>
                <li>
                  <%= link_to dashboard_path(env) do %>
                    <span class="glyphicon">&nbsp;</span> <%= env.name %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
        <li class="<%= 'active' if current_page?(controller: '/deploys', action: 'search') %>">
          <%= link_to "Deploys", search_deploys_path %>
        </li>
        <li class="current-deploys <%= 'active' if current_page?(controller: '/deploys', action: 'active') %>" ng-controller="currentDeployBadgeCtrl">
          <%= link_to active_deploys_path do %>
            Deploying
            <%= content_tag :span, '{{ currentActiveDeploys }}',
                class: 'badge badge-deploys',
                style: 'display: none',
                id: 'currentDeploysBadge',
                data: {count: Deploy.active_count}
            %>
          <% end %>
        </li>
      <% end %>

      <li class="dropdown <%= 'active' if request.path.starts_with?('/admin') %>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if current_user.try(:admin?) %>
            <% if DeployGroup.enabled? %>
              <li><%= link_to "Environments", admin_environments_path %></li>
              <li><%= link_to "Deploy Groups", admin_deploy_groups_path %></li>
            <% end %>
            <li><%= link_to "Projects", admin_projects_path %></li>
          <% end %>
          <li><%= link_to "Commands", admin_commands_path %></li>
          <% if current_user.try(:admin?) %>
            <li><%= link_to "Users", admin_users_path %></li>
            <%= Samson::Hooks.render_views(:admin_menu, self) %>
            <li class="divider"></li>
          <% end %>
          <li><%= link_to "Secrets", admin_secrets_path %></li>
          <% if SecretStorage.backend == Samson::Secrets::HashicorpVaultBackend %>
            <li><%= link_to "Vault Servers", admin_vault_servers_path %></li>
          <% end %>
          <li><%= link_to "Reports", csv_exports_path %></li>
          <% if current_user&.super_admin? %>
            <li><%= link_to "OAuth Applications", oauth_applications_path %></li>
          <% end %>
          <%= Samson::Hooks.render_views(:manage_menu, self) %>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <% if current_user %>
        <li class="dropdown profile">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.gravatar_url, class: "gravatar" %>
            <%= current_user.name %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", profile_path %></li>
            <li><%= link_to "OAuth", access_tokens_path %></li>
            <li><%= link_to "Logout", logout_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_notify_buddy_box.html.erb
<%# see _notify_buddy_box in flowdock and slack_webhooks plugins for examples of using this shared template %>
<%= form_tag form_path do %>
  <div class="alert" style="display: none"></div>

  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title"><%= title %></h3>
    </div>
    <div class="panel-body">
      <div class="col-sm-10">
        <div class="mentions-input-box">
          <%= text_area_tag :message, message, id: id_prefix + 'buddy_request_box' %>
        </div>
        <em>This will send a buddy request to the <strong><%= channels %></strong> <%= channel_type %>.</em>
      </div>
      <div class="col-sm-2">
        <%= submit_tag 'Request a Buddy!', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

<script>
  $(function(){
    var $input = $('#<%= id_prefix %>buddy_request_box');

    // when user hits 'Request', normalize text and submit via ajax
    var $form = $input.parents('form');
    $form.submit(function(e){
      e.preventDefault();

      // normalize mentioned users @[alex](user:1) -> @alex
      $input.mentionsInput('val', function(text){
        $input.val(text.replace(/@\[([^\\]+?)\]\(([^)]+?)\)/g, "@$1"));
      });

      // submit form without leaving the page and show result
      $.ajax({
        url: $form.attr('action'),
        type: $form.attr('method'),
        data: $form.serialize(),
        success: function() {
          $form.find('.alert').addClass('alert-success').text('Message sent!').show()
        },
        error: function(_, _, text) {
          $form.find('.alert').addClass('alert-danger').text('ERROR: ' + text).show()
        }
      });
    });

    // when user types @, show possible user names
    var users = <%= users.to_json.html_safe %>;
    $input.mentionsInput({
      // prefill with what is already there
      defaultValue: $input.val(),

      // when user types after the @ filter down the possible users
      onDataRequest: function (mode, query, callback) {
        var filtered = _.filter(users, function (user) {
          return user.name.toLowerCase().indexOf(query.toLowerCase()) > -1;
        });
        callback.call(this, filtered);
      }
    });
  });
</script>

app/views/shared/_output.html.erb
<div class="output <%= 'hidden' if hide %>">
  <div class="clearfix">
    <div class="btn-toolbar pull-right" id="output-toolbar">
      <div id="output-options" class="btn-group only-active">
        <button class="btn btn-default active" id="output-follow">Follow</button>
        <button class="btn btn-default" id="output-no-follow">Don't Follow</button>
        <button class="btn btn-default" id="output-expand">Expand</button>
      </div>

      <button class="btn btn-default only-finished" id="output-expand-toggle">Expand</button>
      <%= link_to "Download log", [@project, deployable, {format: :text}], class: "btn btn-primary only-finished" %>

      <% if deployable.can_be_stopped_by?(current_user) %>
        <%= stop_button deploy: deployable, project: @project, class: "btn btn-danger only-active" %>
      <% end %>
    </div>
  </div>

  <%= render partial: "jobs/log", locals: { job: job } %>
</div>

app/views/shared/_project_role.html.erb
<%= form_tag project_roles_path(project_id: project.id, user_id: user.id), class: 'autosubmit' do %>
  <% options = [['None', nil]] + UserProjectRole::ROLES.map { |r| [r.name, r.id] } %>
  <% options.each do |name, id| %>
    <%= user_project_role_radio user, name, id, user_project_role_id %>
  <% end %>
<% end %>

app/views/shared/_project_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if active == 'stages' %>">
    <%= link_to "Stages", project %>
  </li>
  <li class="<%= 'active' if active == 'releases' %>">
    <%= link_to "Releases", project_releases_path(project) %>
  </li>
  <% if ENV['DOCKER_FEATURE'] %>
    <li class="<%= 'active' if active == 'builds' %>">
      <%= link_to "Builds", project_builds_path(project) %>
    </li>
  <% end %>
  <li class="<%= 'active' if active == 'deploys' %>">
    <%= link_to "Deploys", project_deploys_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'jobs' %>">
    <%= link_to "Jobs", project_jobs_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'macros' %>">
    <%= link_to "Macros", project_macros_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'webhooks' %>">
    <%= link_to "Webhooks", project_webhooks_path(project) %>
  </li>
  <li class="<%= 'active' if active == 'changelog' %>">
    <%= link_to "Changelog", project_changelog_path(project) %>
  </li>

  <%= Samson::Hooks.render_views(:project_tabs_view, self, { project: @project, active: active }) %>

  <% if admin_for_project? %>
    <li class="<%= 'active' if active == 'users' %>">
      <%= link_to icon_tag('user'), project_users_path(project) %>
    </li>
    <li class="<%= 'active' if active == 'settings' %>">
      <%= link_to icon_tag('cog'), edit_project_path(project) %>
    </li>
  <% end %>
</ul>

app/views/shared/_search_bar.html.erb
<div class="col-md-5 row pull-right search-bar">
  <%= form_tag url, method: 'get', class: 'form-horizontal' do %>
    <%= label_tag :search, 'Search:', class: 'control-label sr-only' %>
    <div class="input-group">
      <%= text_field_tag :search, query, class: 'form-control', placeholder: 'Search' %>
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default" type="button">
          <span class="glyphicon glyphicon-search"></span>
        </button>
      </span>
    </div>
  <% end %>
</div>

app/views/shared/_search_button.html.erb
<div class="col-md-1 clearfix">
  <label>&nbsp;</label>
  <%= submit_tag "Search", class: "btn btn-default form-control" %>
</div>

app/views/shared/_search_query.erb
<div class="col-sm-6" style="padding-left: 0;">
  <%= label_tag "Search" %>
  <%= text_field_tag 'search[query]', params[:search].try(:[], :query), class: "form-control" %>
</div>