plugins/kubernetes/config/routes.rb
# frozen_string_literal: true
Samson::Application.routes.draw do
  resources :projects do
    namespace :kubernetes do
      resources :roles, except: :edit do
        collection do
          post :seed
          get :example
        end
      end
      resources :releases, only: [:index, :show]
    end
  end

  namespace :kubernetes do
    resource :role_verification, only: [:new, :create]
  end

  namespace :admin do
    namespace :kubernetes do
      resources :clusters, except: :destroy do
        member do
          post :seed_ecr
        end
      end
      resources :deploy_group_roles do
        collection do
          post :seed
        end
      end
    end
  end
end

plugins/kubernetes/app/models/kubernetes/api/job.rb
# frozen_string_literal: true
module Kubernetes
  module Api
    class Job
      def initialize(api_job)
        @job = api_job
      end

      def name
        @job.metadata.try(:name)
      end

      def namespace
        @job.metadata.try(:namespace)
      end

      def failure?
        @job.status == 'Failure'
      end

      def complete?
        (@job.status.conditions || []).detect { |c| break c['status'] == 'True' if c['type'] == 'Complete' }
      end
    end
  end
end

plugins/kubernetes/app/models/kubernetes/api/pod.rb
# frozen_string_literal: true
module Kubernetes
  module Api
    class Pod
      def initialize(api_pod, client: nil)
        @pod = api_pod
        @client = client
      end

      def name
        @pod.metadata.name
      end

      def namespace
        @pod.metadata.namespace
      end

      def live?
        completed? || (phase == 'Running' && ready?)
      end

      def completed?
        phase == 'Succeeded'
      end

      def failed?
        phase == 'Failed'
      end

      def restarted?
        @pod.status.containerStatuses.try(:any?) { |s| s.restartCount.positive? }
      end

      def phase
        @pod.status.phase
      end

      def reason
        reasons = []
        reasons.concat @pod.status.conditions.try(:map, &:reason).to_a
        reasons.concat @pod.status.containerStatuses.
          try(:map) { |s| s.to_h.fetch(:state).values.map { |s| s[:reason] } }.
          to_a
        reasons.reject(&:blank?).uniq.join("/").presence || "Unknown"
      end

      def deploy_group_id
        labels.deploy_group_id.to_i
      end

      def role_id
        labels.role_id.to_i
      end

      def containers
        @pod.spec.containers.map(&:to_h)
      end

      # tries to get logs from current or previous pod depending on if it restarted
      def logs(container)
        fetch_logs(container, previous: restarted?)
      rescue KubeException # not found or pod is initializing
        begin
          fetch_logs(container, previous: !restarted?)
        rescue KubeException
          nil
        end
      end

      def events_indicate_failure?
        bad = events.reject { |e| e.type == 'Normal' }
        readiness_failures, other_failures = bad.partition do |e|
          e.reason == "Unhealthy" && e.message =~ /\A\S+ness probe failed/
        end
        other_failures.any? || readiness_failures.any? { |event| probe_failed_to_often?(event) }
      end

      def events
        @events ||= @client.get_events(
          namespace: namespace,
          field_selector: "involvedObject.name=#{name}"
        ).select do |event|
          # compare strings to avoid parsing time '2017-03-31T22:56:20Z'
          event.metadata.creationTimestamp >= @pod.status.startTime.to_s
        end
      end

      def init_containers
        return [] unless containers = @pod.dig(:metadata, :annotations, :'pod.alpha.kubernetes.io/init-containers')
        JSON.parse(containers, symbolize_names: true)
      end

      private

      # if the pod is still running we stream the logs until it times out to get as much info as possible
      # necessary since logs often hang for a while even if the pod is already done
      def fetch_logs(container, previous:)
        if previous
          @client.get_pod_log(name, namespace, container: container, previous: true)
        else
          result = "".dup
          begin
            timeout_logs do
              @client.watch_pod_log(name, namespace, container: container).each do |log|
                result << log << "\n"
              end
            end
          rescue Timeout::Error
            result << "... log streaming timeout"
          end
          result
        end
      end

      # easy stub
      def timeout_logs(&block)
        Timeout.timeout(Integer(ENV['KUBERNETES_LOG_TIMEOUT'] || '20'), &block)
      end

      def probe_failed_to_often?(event)
        probe =
          case event.message
          when /\AReadiness/ then :readinessProbe
          when /\ALiveliness/ then :livelinessProbe
          else raise("Unknown probe #{event.message}")
          end
        event.count >= failure_threshold(probe)
      end

      # per http://kubernetes.io/docs/api-reference/v1/definitions/ default is 3
      # by default checks every 10s so that gives us 30s to pass
      def failure_threshold(probe)
        @pod.dig(:spec, :containers, 0, probe, :failureThreshold) || 3
      end

      def labels
        @pod.metadata.try(:labels)
      end

      def ready?
        if @pod.status.conditions.present?
          ready = @pod.status.conditions.find { |c| c['type'] == 'Ready' }
          ready && ready['status'] == 'True'
        else
          false
        end
      end
    end
  end
end

plugins/kubernetes/app/models/kubernetes/cluster.rb
# frozen_string_literal: true
require 'kubeclient'

module Kubernetes
  class Cluster < ActiveRecord::Base
    self.table_name = 'kubernetes_clusters'

    IP_PREFIX_PATTERN = /\A(?:[\d]{1,3}\.){0,2}[\d]{1,3}\z/ # also used in js

    has_many :cluster_deploy_groups, class_name: 'Kubernetes::ClusterDeployGroup', foreign_key: :kubernetes_cluster_id
    has_many :deploy_groups, through: :cluster_deploy_groups

    validates :name, presence: true, uniqueness: true
    validates :config_filepath, presence: true
    validates :config_context, presence: true
    validates :ip_prefix, format: IP_PREFIX_PATTERN, allow_blank: true
    validate :test_client_connection

    def client
      @client ||= build_client :default
    end

    def extension_client
      @extension_client ||= build_client 'extensions/v1beta1'
    end

    def context
      @context ||= kubeconfig.context(config_context)
    end

    def namespaces
      client.get_namespaces.map { |ns| ns.metadata.name } - %w[kube-system]
    end

    def namespace_exists?(namespace)
      connection_valid? && namespaces.include?(namespace)
    rescue KubeException
      false
    end

    def kubeconfig
      @kubeconfig ||= Kubeclient::Config.read(config_filepath)
    end

    private

    def connection_valid?
      client.api_valid?
    rescue KubeException, Errno::ECONNREFUSED
      false
    end

    def build_client(type)
      endpoint = context.api_endpoint
      if type == :default
        type = context.api_version
      else
        endpoint = endpoint.sub(/\/api$/, '') + '/apis'
      end

      Kubeclient::Client.new(
        endpoint,
        type,
        ssl_options: context.ssl_options,
        auth_options: context.auth_options
      )
    end

    def test_client_connection
      if File.file?(config_filepath)
        unless connection_valid?
          errors.add(:config_context, "Could not connect to API Server")
        end
      else
        errors.add(:config_filepath, "File does not exist")
      end
    end
  end
end

plugins/kubernetes/app/models/kubernetes/cluster_deploy_group.rb
# frozen_string_literal: true
module Kubernetes
  class ClusterDeployGroup < ActiveRecord::Base
    self.table_name = 'kubernetes_cluster_deploy_groups'

    belongs_to :cluster, class_name: 'Kubernetes::Cluster', foreign_key: :kubernetes_cluster_id
    belongs_to :deploy_group, inverse_of: :cluster_deploy_group

    validates :cluster, presence: true
    validates :deploy_group, presence: true
    validates :namespace, presence: true
    validate :validate_namespace_exists

    private

    def validate_namespace_exists
      if cluster && namespace.present? && !cluster.namespace_exists?(namespace)
        errors.add(:namespace, "named '#{namespace}' does not exist")
      end
    end
  end
end

plugins/kubernetes/app/models/kubernetes/role_config_file.rb
# frozen_string_literal: true
module Kubernetes
  # Represents a Kubernetes configuration file for a project role.
  # A configuration file can have for example both a Deployment spec and a Service spec
  # ... this is no longer needed ... merge into release_doc
  class RoleConfigFile
    attr_reader :path, :elements

    DEPLOY_KINDS = ['Deployment', 'DaemonSet'].freeze
    JOB_KINDS = ['Job'].freeze
    PRIMARY_KINDS = (DEPLOY_KINDS + JOB_KINDS + ['Pod']).freeze
    SERVICE_KINDS = ['Service'].freeze
    PREREQUISITE = [:metadata, :annotations, :'samson/prerequisite'].freeze

    def initialize(content, path)
      @path = path

      if content.blank?
        raise Samson::Hooks::UserError, "does not contain config file '#{path}'"
      end

      begin
        @elements = Array.wrap(Kubernetes::Util.parse_file(content, path)).compact.map(&:deep_symbolize_keys)
      rescue
        raise Samson::Hooks::UserError, "Error found when parsing #{path}\n#{$!.message}"
      end

      if errors = Kubernetes::RoleVerifier.new(@elements).verify
        raise Samson::Hooks::UserError, "Error found when parsing #{path}\n#{errors.join("\n")}"
      end
    end

    def deploy
      find_by_kind(DEPLOY_KINDS)
    end

    def service
      find_by_kind(SERVICE_KINDS)
    end

    def job
      find_by_kind(JOB_KINDS)
    end

    private

    def find_by_kind(kinds)
      @elements.detect { |doc| kinds.include?(doc[:kind]) }
    end
  end
end

plugins/kubernetes/app/controllers/admin/kubernetes/clusters_controller.rb
# frozen_string_literal: true
class Admin::Kubernetes::ClustersController < ApplicationController
  before_action :authorize_admin!
  before_action :authorize_super_admin!, except: [:index, :show, :seed_ecr]

  before_action :find_cluster, only: [:show, :edit, :update, :seed_ecr]
  before_action :load_default_config_file, only: [:new, :edit, :update, :create]

  def new
    @cluster = ::Kubernetes::Cluster.new(config_filepath: @config_file)
    render :edit
  end

  def create
    @cluster = ::Kubernetes::Cluster.new(new_cluster_params)
    if @cluster.save
      redirect_to [:admin, @cluster], notice: "Saved!"
    else
      render :edit
    end
  end

  def index
    @clusters = ::Kubernetes::Cluster.all.sort_by { |c| Samson::NaturalOrder.convert(c.name) }
  end

  def show
  end

  def edit
  end

  def update
    @cluster.assign_attributes(new_cluster_params)
    if @cluster.save
      redirect_to({action: :index}, notice: "Saved!")
    else
      render :edit
    end
  end

  def seed_ecr
    SamsonAwsEcr::Engine.refresh_credentials
    @cluster.namespaces.each do |namespace|
      update_secret namespace
    end
    redirect_to({action: :index}, notice: "Seeded!")
  end

  private

  def find_cluster
    @cluster = ::Kubernetes::Cluster.find(params[:id])
  end

  def new_cluster_params
    params.require(:kubernetes_cluster).permit(
      :name, :config_filepath, :config_context, :description, :ip_prefix, deploy_group_ids: []
    )
  end

  def load_default_config_file
    @config_file = if @cluster
      @cluster.config_filepath
    elsif file = ENV['KUBE_CONFIG_FILE']
      File.expand_path(file)
    elsif last_cluster = ::Kubernetes::Cluster.last
      last_cluster.config_filepath
    end

    @context_options = Kubeclient::Config.read(@config_file).contexts if @config_file
    @context_options ||= []
  end

  # same as this does under the hood:
  # http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry
  # kubectl create secret docker-registry kube-ecr-auth --docker-server=X --docker-username=X --docker-password=X
  def update_secret(namespace)
    docker_config = DockerRegistry.all.each_with_object({}) do |r, h|
      h[r.host] = { username: r.username, password: r.password }
    end

    secret = {
      kind: "Secret",
      apiVersion: "v1",
      metadata: {
        name: "kube-ecr-auth",
        namespace: namespace,
        annotations: {
          via: "Samson",
          created_at: Time.now.to_s(:db)
        }
      },
      data: {
        ".dockercfg" => Base64.encode64(JSON.dump(docker_config))
      },
      type: "kubernetes.io/dockercfg"
    }

    if secret_exist?(secret)
      @cluster.client.update_secret(secret)
    else
      @cluster.client.create_secret(secret)
    end
  end

  def secret_exist?(secret)
    @cluster.client.get_secret(secret.fetch(:metadata).fetch(:name), secret.fetch(:metadata).fetch(:namespace))
    true
  rescue KubeException
    false
  end
end

plugins/kubernetes/app/controllers/admin/kubernetes/deploy_group_roles_controller.rb
# frozen_string_literal: true
class Admin::Kubernetes::DeployGroupRolesController < ApplicationController
  before_action :find_role, only: [:show, :edit, :update, :destroy]
  before_action :find_stage, only: [:seed]
  before_action :authorize_project_admin!, except: [:index, :show, :new]

  def new
    attributes = (params[:kubernetes_deploy_group_role] ? deploy_group_role_params : {})
    @deploy_group_role = ::Kubernetes::DeployGroupRole.new(attributes)
  end

  def create
    @deploy_group_role = ::Kubernetes::DeployGroupRole.new(deploy_group_role_params)
    if @deploy_group_role.save
      redirect_back_or [:admin, @deploy_group_role]
    else
      render :new, status: 422
    end
  end

  def index
    @deploy_group_roles = ::Kubernetes::DeployGroupRole
    [:project_id, :deploy_group_id].each do |scope|
      if id = params.dig(:search, scope).presence
        @deploy_group_roles = @deploy_group_roles.where(scope => id)
      end
    end
    @deploy_group_roles = @deploy_group_roles.all
  end

  def show
  end

  def edit
  end

  def update
    @deploy_group_role.assign_attributes(
      deploy_group_role_params.except(:project_id, :deploy_group_id, :kubernetes_role_id)
    )
    if @deploy_group_role.save
      redirect_back_or [:admin, @deploy_group_role]
    else
      render :edit, status: 422
    end
  end

  def destroy
    @deploy_group_role.destroy
    redirect_to action: :index
  end

  def seed
    success = ::Kubernetes::DeployGroupRole.seed!(@stage)
    options = if success
      {notice: "Missing roles seeded."}
    else
      {alert: "Some roles failed to seed, fill them in manually."}
    end
    redirect_to [@stage.project, @stage], options
  end

  private

  def current_project
    if action_name == 'create'
      Project.find(deploy_group_role_params.require(:project_id))
    elsif action_name == 'seed'
      @stage.project
    else
      @deploy_group_role.project
    end
  end

  def find_role
    @deploy_group_role = ::Kubernetes::DeployGroupRole.find(params.require(:id))
  end

  def find_stage
    @stage = Stage.find(params.require(:stage_id))
  end

  def deploy_group_role_params
    params.require(:kubernetes_deploy_group_role).permit(
      :kubernetes_role_id, :ram, :cpu, :replicas, :project_id, :deploy_group_id
    )
  end
end

plugins/kubernetes/app/controllers/kubernetes/releases_controller.rb
# frozen_string_literal: true
class Kubernetes::ReleasesController < ApplicationController
  include CurrentProject

  before_action :authorize_project_deployer!

  def index
    @kubernetes_releases = current_project.kubernetes_releases.order('id desc')
  end

  def show
    @kubernetes_release = current_project.kubernetes_releases.find(params.require(:id))
  end
end

plugins/kubernetes/app/controllers/kubernetes/role_verifications_controller.rb
# frozen_string_literal: true
class Kubernetes::RoleVerificationsController < ApplicationController
  def new
  end

  def create
    input = params[:role].presence || '{}'
    filename = (input.start_with?('{', '[') ? 'test.json' : 'test.yml')
    begin
      Kubernetes::RoleConfigFile.new(input, filename)
    rescue Samson::Hooks::UserError
      @errors = $!.message
    else
      flash.now[:notice] = "Valid!"
    end
    render :new
  end
end

plugins/kubernetes/app/controllers/kubernetes/roles_controller.rb
# frozen_string_literal: true
class Kubernetes::RolesController < ApplicationController
  include CurrentProject

  DEFAULT_BRANCH = 'master'

  before_action :authorize_project_deployer!
  before_action :authorize_project_admin!, except: [:index, :show, :example]
  before_action :find_role, only: [:show, :update, :destroy]

  def index
    @roles = ::Kubernetes::Role.not_deleted.where(project: current_project).order('name desc').to_a
    respond_to do |format|
      format.html
      format.json { render json: @roles, root: false }
    end
  end

  def seed
    begin
      Kubernetes::Role.seed!(@project, params[:ref].presence || DEFAULT_BRANCH)
    rescue Samson::Hooks::UserError
      flash[:error] = $!.message
    end
    redirect_to action: :index
  end

  def example
  end

  def new
    @role = Kubernetes::Role.new
  end

  def create
    @role = Kubernetes::Role.new(role_params.merge(project: @project))
    if @role.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def update
    if @role.update_attributes(role_params)
      redirect_to action: :index
    else
      render :show
    end
  end

  def destroy
    @role.soft_delete!
    redirect_to action: :index
  end

  private

  def find_role
    @role = Kubernetes::Role.not_deleted.find(params[:id])
  end

  def role_params
    params.require(:kubernetes_role).permit(:name, :config_file, :service_name, :resource_name)
  end
end

plugins/kubernetes/app/views/admin/kubernetes/deploy_group_roles/_form.html.erb
<%= form_for [:admin, @deploy_group_role], html: { class: "form-horizontal" } do |form| %>
  <%= redirect_to_field %>
  <%= render 'shared/errors', object: @deploy_group_role %>
  <% defaults = @deploy_group_role.kubernetes_role.try(:defaults) || {} %>

  <fieldset>
    <%= form.input :deploy_group_id do %>
      <%= form.select :deploy_group_id, DeployGroup.pluck(:name, :id), {}, class: "form-control", disabled: @deploy_group_role.persisted? %>
    <% end %>

    <%= form.input :project_id do %>
      <% projects = current_user.administrated_projects.with_kubernetes_roles.pluck(:name, :id) %>
      <%= form.select :project_id, projects, {}, class: "form-control", disabled: @deploy_group_role.persisted? %>
    <% end %>

    <%= form.input :kubernetes_role_id, label: 'Role' do %>
      <%= form.select :kubernetes_role_id, [['Loading ...', @deploy_group_role.kubernetes_role_id]], {}, class: "form-control", disabled: @deploy_group_role.persisted? %>
    <% end %>

    <% [[:replicas, "Replicas"], [:cpu, 'CPU Cores'], [:ram, 'Ram in MB']].each do |column, label| %>
      <%= form.input column, label: label do %>
        <%= form.text_field column, class: "form-control" %>
        <% if default = defaults[column] %>
          Default: <%= default %>
        <% end %>
      <% end %>
    <% end %>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= form.submit @deploy_group_role.persisted? ? 'Save' : 'Create', class: "btn btn-primary" %>
        <%= link_to_delete [:admin, @deploy_group_role], class: 'btn btn-default' if @deploy_group_role.persisted? %>
        <%= link_to "Cancel", :back, class: 'btn btn-default' %>
        <%= link_to_history @deploy_group_role %>
      </div>
    </div>
  </fieldset>
<% end %>

<script>
  // change selectable roles when project changes, since every project has different roles
  $(function(){
    var project_data = <%= Kubernetes::Role.not_deleted.pluck(:project_id, :id, :name).group_by(&:first).to_json.html_safe %>
    $('#kubernetes_deploy_group_role_project_id').change(function () {
      var $role_select = $('#kubernetes_deploy_group_role_kubernetes_role_id');
      var project_id = parseInt($(this).val(), 10);
      var val = parseInt($role_select.val(), 10);
      var roles = project_data[project_id];

      // clear out previous options and refresh the select
      $role_select.html('').val('');

      // fill in currently selectable roles, keeping the current selection for edit or failed create
      $.each(roles, function(i, e){
        $role_select.append($("<option>", { value: e[1], html: e[2], selected: (e[1] === val) }));
      });

      // highlight the changed select so user sees the effect
      $role_select.effect("highlight", {color: "#ffffe0"}, 500);
    }).trigger('change');
  });
</script>

plugins/kubernetes/app/views/admin/kubernetes/deploy_group_roles/edit.html.erb
<%= page_title "Edit Kubernetes Deploy Group Role" %>

<section>
  <%= render 'form' %>
</section>

plugins/kubernetes/app/views/admin/kubernetes/deploy_group_roles/index.html.erb
<%= page_title "Kubernetes Deploy Group Roles" %>

<%= form_tag '?', method: :get, class: 'clearfix' do %>
  <div class="col-sm-3">
    <%= label_tag "Project" %><br/>
    <% possible = Project.where(id: Kubernetes::DeployGroupRole.pluck('distinct project_id')).order('name asc') %>
    <% options = options_for_select(possible.pluck(:name, :id), params[:search].try(:[], :project_id)) %>
    <%= select_tag 'search[project_id]', options, include_blank: "", title: "", class: "form-control selectpicker", data: {live_search: true} %>
  </div>
  <div class="col-sm-3">
    <%= label_tag "Deploy Group" %><br/>
    <% possible = DeployGroup.where(id: Kubernetes::DeployGroupRole.pluck('distinct deploy_group_id')).sort_by(&:natural_order) %>
    <% options = options_for_select(possible.map { |dg| [dg.name, dg.id] }, params[:search].try(:[], :deploy_group_id)) %>
    <%= select_tag 'search[deploy_group_id]', options, include_blank: "", class: "form-control", style: "background-color: white; width: 100%; height: 35px" %>
  </div>
  <%= render 'shared/search_button' %>
<% end %>
<br/>

<section class="clearfix tabs">
  <div class="table table-hover table-condensed">

    <table class="table">
      <tr>
        <th>Project</th>
        <th>Deploy Group</th>
        <th>Role</th>
        <th>CPU</th>
        <th>RAM</th>
        <th>Replicas</th>
        <th>Actions</th>
      </tr>

      <% @deploy_group_roles.each do |deploy_group_role| %>
        <tr>
          <td><%= link_to deploy_group_role.project.name, deploy_group_role.project %></td>
          <td><%= link_to deploy_group_role.deploy_group.name, [:admin, deploy_group_role.deploy_group] %></td>
          <td><%= link_to deploy_group_role.kubernetes_role.name, [deploy_group_role.project, deploy_group_role.kubernetes_role] %></td>
          <td><%= deploy_group_role.cpu %></td>
          <td><%= deploy_group_role.ram %></td>
          <td><%= deploy_group_role.replicas %></td>
          <td>
            <% if current_user.admin_for?(deploy_group_role.project) %>
              <%= link_to 'Edit', edit_admin_kubernetes_deploy_group_role_path(deploy_group_role) %>
            <% end %>
          </td>
        </tr>
      <% end %>

      <tr>
        <td colspan="3">Total</td>
        <td><%= @deploy_group_roles.map(&:cpu).sum %></td>
        <td><%= @deploy_group_roles.map(&:ram).sum %></td>
        <td><%= @deploy_group_roles.map(&:replicas).sum %></td>
      </tr>
    </table>
  </div>

  <div class="admin-actions">
    <div class="pull-right">
      <%= link_to "New", new_admin_kubernetes_deploy_group_role_path, class: "btn btn-default" %>
    </div>
  </div>
</section>

plugins/kubernetes/app/views/admin/kubernetes/deploy_group_roles/new.html.erb
<%= page_title "New Kubernetes Deploy Group Role" %>

<section>
  <%= render 'form' %>
</section>

plugins/kubernetes/app/views/admin/kubernetes/deploy_group_roles/show.html.erb
<%= page_title "Kubernetes Deploy Group Role" %>

<section class="form-horizontal">
  <div class="form-group">
    <label class="col-lg-2 control-label">Role</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= link_to @deploy_group_role.kubernetes_role.name, [@deploy_group_role.project, @deploy_group_role.kubernetes_role] %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">Project</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= link_to @deploy_group_role.project.name, project_path(@deploy_group_role.project) %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">Deploy Group</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= link_to @deploy_group_role.deploy_group.name, [:admin, @deploy_group_role.deploy_group] %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">Replicas</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= @deploy_group_role.replicas %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">CPU</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= @deploy_group_role.cpu %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-lg-2 control-label">RAM</label>
    <div class="col-lg-4">
      <p class="form-control-static"><%= @deploy_group_role.ram %> MB</p>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <% if current_user.admin_for?(@deploy_group_role.project) %>
        <%= link_to "Edit", edit_admin_kubernetes_deploy_group_role_path(@deploy_group_role), class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back", admin_kubernetes_deploy_group_roles_path, class: "btn btn-default" %>
    </div>
  </div>
</section>