config/routes.rb
# frozen_string_literal: true
Samson::Application.routes.draw do
  root to: 'projects#index'

  namespace :api do
    resources :deploys, only: [:index, :show] do
      collection do
        get :active_count
      end
    end

    resources :deploy_groups, only: [:index]

    resources :projects, only: [:index] do
      resources :automated_deploys, only: [:create]
      resources :builds, only: [:create]
      resources :deploys, only: [:index]
      resources :stages, only: [:index] do
        member do
          get :deploy_groups, to: 'deploy_groups#index'
        end
      end
    end

    resources :stages, only: [] do
      resources :deploys, only: [:index]
      post :clone, to: 'stages#clone'
    end

    resources :locks, only: [:index, :create, :destroy]
    delete '/locks', to: 'locks#destroy_via_resource'

    resources :users, only: [:destroy]
  end

  resources :projects, except: [:destroy] do
    resources :jobs, only: [:index, :show, :destroy]

    resources :macros, only: [:index, :new, :create, :edit, :update, :destroy] do
      member { post :execute }
    end

    resources :builds, only: [:show, :index, :new, :create, :edit, :update] do
      member do
        post :build_docker_image
      end
    end

    resource :build_command, only: [:show, :update]

    resources :deploys, only: [:index, :show, :destroy] do
      collection do
        get :active
      end

      member do
        post :buddy_check
        get :changeset
      end
    end

    resources :releases, only: [:show, :index, :new, :create], id: Release::ROUTE_REGEX

    resources :stages do
      collection do
        patch :reorder
      end

      member do
        get :clone, to: 'stages#clone'
      end

      resources :deploys, only: [:new, :create] do
        collection do
          post :confirm
        end
      end

      resource :commit_statuses, only: [:show]
    end

    resource :changelog, only: [:show]
    resource :stars, only: [:create]
    resources :webhooks, only: [:index, :create, :destroy]
    resources :outbound_webhooks, only: [:create, :destroy]
    resources :references, only: [:index]
    resources :users, only: [:index, :update]

    member do
      get :deploy_group_versions
    end
  end

  resources :project_roles, only: [:create]
  resources :streams, only: [:show]
  resources :locks, only: [:create, :destroy]

  resources :deploys, only: [:index] do
    collection do
      get :active
      get :search
    end
  end

  resources :deploy_groups, only: [:show]

  resource :profile, only: [:show, :update]

  resources :access_tokens, only: [:index, :new, :create, :destroy]

  resources :versions, only: [:index]

  get '/auth/github/callback', to: 'sessions#github'
  get '/auth/google/callback', to: 'sessions#google'
  post '/auth/ldap/callback', to: 'sessions#ldap'
  get '/auth/gitlab/callback', to: 'sessions#gitlab'
  get '/auth/failure', to: 'sessions#failure'

  get '/jobs/enabled', to: 'jobs#enabled', as: :enabled_jobs

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  resources :csv_exports, only: [:index, :new, :create, :show]
  resources :dashboards, only: [:show] do
    member do
      get :deploy_groups
    end
  end

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy] do
      resource :user_merges, only: [:new, :create]
    end
    resources :projects, only: [:index, :destroy]
    resources :commands, except: [:edit]
    resources :secrets, except: [:edit]
    resources :vault_servers, except: [:edit] do
      member do
        post :sync
      end
    end
    resources :environments, except: [:edit]
    resources :deploy_groups do
      member do
        post :deploy_all
        get :create_all_stages_preview
        post :create_all_stages
        post :merge_all_stages
        post :delete_all_stages
      end
    end
  end

  namespace :integrations do
    post "/circleci/:token" => "circleci#create", as: :circleci_deploy
    post "/travis/:token" => "travis#create", as: :travis_deploy
    post "/semaphore/:token" => "semaphore#create", as: :semaphore_deploy
    post "/tddium/:token" => "tddium#create", as: :tddium_deploy
    post "/jenkins/:token" => "jenkins#create", as: :jenkins_deploy
    post "/buildkite/:token" => "buildkite#create", as: :buildkite_deploy
    post "/github/:token" => "github#create", as: :github_deploy
  end

  get '/ping', to: 'ping#show'

  resources :access_requests, only: [:new, :create]

  mount SseRailsEngine::Engine, at: '/streaming'

  use_doorkeeper # adds oauth/* routes
  resources :oauth_test, only: [:index, :show] if %w[development test].include?(Rails.env)
end

app/models/stage.rb
# frozen_string_literal: true
class Stage < ActiveRecord::Base
  AUTOMATED_NAME = 'Automated Deploys'

  has_soft_deletion default_scope: true unless self < SoftDeletion::Core

  include Permalinkable
  include HasCommands

  has_paper_trail skip: [:order, :updated_at, :created_at]

  belongs_to :project, touch: true

  has_many :deploys, dependent: :destroy
  has_many :webhooks, dependent: :destroy
  has_many :outbound_webhooks, dependent: :destroy

  belongs_to :template_stage, class_name: "Stage"
  has_many :clones, class_name: "Stage", foreign_key: "template_stage_id"

  has_one :lock, as: :resource

  has_many :command_associations, autosave: true, class_name: 'StageCommand', dependent: :destroy
  has_many :commands, -> { order('stage_commands.position ASC') },
    through: :command_associations, auto_include: false

  has_many :deploy_groups_stages, dependent: :destroy
  has_many :deploy_groups, through: :deploy_groups_stages

  default_scope { order(:order) }

  validates :name, presence: true, uniqueness: { scope: [:project, :deleted_at] }

  # n emails separated by ;
  email = '([^\s;]+@[^\s;]+)'
  validates :notify_email_address, format: /\A#{email}((\s*;\s*)?#{email}?)*\z/, allow_blank: true
  validate :validate_deploy_group_selected

  before_create :ensure_ordering
  after_destroy :destroy_deploy_groups_stages
  after_destroy :destroy_stage_pipeline
  after_soft_delete :destroy_deploy_groups_stages
  after_soft_delete :destroy_stage_pipeline

  scope :cloned, -> { where.not(template_stage_id: nil) }

  def self.reset_order(new_order)
    transaction do
      new_order.each.with_index { |stage_id, index| Stage.update stage_id.to_i, order: index.to_i }
    end
  end

  def self.build_clone(old_stage)
    new(old_stage.attributes.except("id")).tap do |new_stage|
      Samson::Hooks.fire(:stage_clone, old_stage, new_stage)
      new_stage.command_ids = old_stage.command_ids
      new_stage.template_stage = old_stage
    end
  end

  def self.deployed_on_release
    where(deploy_on_release: true)
  end

  def self.where_reference_being_deployed(reference)
    joins(deploys: :job).where(
      deploys: { reference: reference },
      jobs: { status: Job::ACTIVE_STATUSES }
    )
  end

  def current_deploy
    return @current_deploy if defined?(@current_deploy)
    @current_deploy = deploys.active.first
  end

  def last_deploy
    return @last_deploy if defined?(@last_deploy)
    @last_deploy = deploys.first
  end

  def last_successful_deploy
    return @last_successful_deploy if defined?(@last_successful_deploy)
    @last_successful_deploy = deploys.successful.first
  end

  # comparing commits might be better ...
  def current_release?(release)
    last_successful_deploy&.reference == release.version
  end

  def create_deploy(user, attributes = {})
    before_command = attributes.delete(:before_command)
    deploys.create(attributes.merge(release: !no_code_deployed, project: project)) do |deploy|
      commands = before_command.to_s.dup << script
      deploy.build_job(project: project, user: user, command: commands, commit: deploy.reference)
    end
  end

  # The next stage for the project. If this is the last stage, returns nil.
  def next_stage
    stages = project.stages.to_a
    stages[stages.index(self) + 1]
  end

  def notify_email_addresses
    notify_email_address.to_s.split(/\s*;\s*/).map(&:strip)
  end

  # this logic is replicated in SQL inside of app/jobs/csv_export_job.rb#filter_deploys for report filtering
  # update the SQL query as well when editing this method
  def production?
    if DeployGroup.enabled?
      deploy_groups.empty? ? super : environments.any?(&:production?)
    else
      super
    end
  end

  def deploy_requires_approval?
    BuddyCheck.enabled? && !no_code_deployed? && production?
  end

  def automated_failure_emails(deploy)
    return if !email_committers_on_automated_deploy_failure? && static_emails_on_automated_deploy_failure.blank?
    return unless deploy.failed?
    return unless deploy.user.integration?
    last_deploy = deploys.finished_naturally.prior_to(deploy).first
    return if last_deploy.try(:failed?)

    emails = []

    # static notification
    emails.concat static_emails_on_automated_deploy_failure.to_s.split(/, ?/)

    # authors of commits after last successful deploy
    if email_committers_on_automated_deploy_failure?
      changeset = deploy.changeset_to(last_deploy)
      emails.concat changeset.commits.map(&:author_email).compact
    end

    emails.uniq.presence
  end

  # we record a version on every script change, but do not update the stage ... see Command#trigger_stage_change
  def script_updated_after?(time)
    versions.last&.created_at&.> time
  end

  # in theory this should not get called multiple times for the same state,
  # but adding a bit of extra sanity checking to make sure nothing slips in
  def record_script_change
    state_to_record = object_attrs_for_paper_trail(attributes_before_change)
    if @last_recorded_state == state_to_record
      raise "Trying to record the same state twice"
    end

    @last_recorded_state = state_to_record
    record_update true
  end

  def destroy
    mark_for_destruction
    super
  end

  def deploy_group_names
    DeployGroup.enabled? ? deploy_groups.select(:name).sort_by(&:natural_order).map(&:name) : []
  end

  def environments
    DeployGroup.enabled? ? deploy_groups.map(&:environment).uniq : []
  end

  def command_ids=(value)
    @command_ids_changed = (command_ids != value.map(&:to_i))
    super
  end

  def influencing_stage_ids
    deploy_group_ids = deploy_groups_stages.reorder(nil).pluck(:deploy_group_id)
    stage_ids = DeployGroupsStage.reorder(nil).where(deploy_group_id: deploy_group_ids).pluck('distinct stage_id')
    Stage.reorder(nil).where(id: stage_ids, project_id: project_id).pluck(:id)
  end

  private

  def permalink_base
    name
  end

  def permalink_scope
    Stage.unscoped.where(project_id: project_id)
  end

  def ensure_ordering
    return unless project
    self.order = project.stages.maximum(:order).to_i + 1
  end

  # overwrites papertrail to record script
  def object_attrs_for_paper_trail(attributes)
    super(attributes.merge('script' => script))
  end

  # DeployGroupsStage has no ids so the default dependent: :destroy fails
  def destroy_deploy_groups_stages
    DeployGroupsStage.where(stage_id: id).delete_all
  end

  def destroy_stage_pipeline
    (project.stages - [self]).each do |s|
      if s.next_stage_ids.delete(id)
        s.save(validate: false)
      end
    end
  end

  # overwrites papertrail to record when command_ids were changed but not trigger multiple versions per save
  def changed_notably?
    super || @command_ids_changed
  end

  def validate_deploy_group_selected
    if DeployGroup.enabled? && name != AUTOMATED_NAME && deploy_groups.empty?
      errors.add(:deploy_groups, "need to be selected")
    end
  end
end

app/controllers/api/stages_controller.rb
# frozen_string_literal: true
class Api::StagesController < Api::BaseController
  include CurrentProject

  before_action :require_project

  def index
    render json: @project.stages
  end

  def clone
    new_stage = Stage.build_clone(stage_to_clone)
    new_stage.name = stage_name
    new_stage.deploy_groups = deploy_groups if deploy_groups.any?
    if new_stage.save
      render json: new_stage, status: 201
    else
      render json: new_stage.errors, status: 422
    end
  end

  private

  def stage_to_clone
    Stage.find_by_param!(params.require(:stage_id))
  end

  def stage_name
    params.fetch(:stage_name, "Copy of #{stage_to_clone.name}")
  end

  def deploy_group_ids
    params.fetch(:deploy_group_ids, [])
  end

  def deploy_groups
    DeployGroup.where(id: deploy_group_ids)
  end
end

app/controllers/stages_controller.rb
# frozen_string_literal: true
class StagesController < ApplicationController
  include CurrentProject

  skip_around_action :login_user, if: :badge?

  before_action :authorize_project_deployer!, except: [:show]
  before_action :authorize_project_admin!, except: [:index, :show]
  before_action :check_token, if: :badge?
  before_action :find_stage, only: [:show, :edit, :update, :destroy, :clone]

  def index
    @stages = @project.stages

    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html do
        @deploys = @stage.deploys.page(params[:page])
      end
      format.svg do
        badge =
          if deploy = @stage.last_successful_deploy
            "#{badge_safe(@stage.name)}-#{badge_safe(deploy.short_reference)}-green"
          else
            "#{badge_safe(@stage.name)}-None-red"
          end
        redirect_to "https://img.shields.io/badge/#{badge}.svg"
      end
    end
  end

  def new
    @stage = @project.stages.build(command_ids: Command.global.pluck(:id))
  end

  def create
    # Need to ensure project is already associated
    @stage = @project.stages.build
    @stage.attributes = stage_params

    if @stage.save
      redirect_to [@project, @stage]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @stage.update_attributes(stage_params)
      redirect_to [@project, @stage]
    else
      render :edit
    end
  end

  def destroy
    @stage.soft_delete!
    redirect_to @project
  end

  def reorder
    Stage.reset_order(params[:stage_id])
    head :ok
  end

  def clone
    @stage = Stage.build_clone(@stage)
    render :new
  end

  private

  def badge_safe(string)
    CGI.escape(string).
      gsub('+', '%20').
      gsub(/-+/, '--')
  end

  def check_token
    return if Rack::Utils.secure_compare(params[:token], Rails.application.config.samson.badge_token)
    head :not_found
  end

  def badge?
    action_name == 'show' && request.format == Mime[:svg]
  end

  def stage_params
    params.require(:stage).permit(stage_permitted_params)
  end

  def find_stage
    return if @stage = current_project.stages.find_by_param(params[:id])
    badge? ? head(:not_found) : raise(ActiveRecord::RecordNotFound)
  end

  def stage_permitted_params
    [
      :name,
      :command,
      :confirm,
      :permalink,
      :dashboard,
      :production,
      :notify_email_address,
      :deploy_on_release,
      :email_committers_on_automated_deploy_failure,
      :static_emails_on_automated_deploy_failure,
      :no_code_deployed,
      :is_template,
      :run_in_parallel,
      :cancel_queued_deploys,
      {
        deploy_group_ids: [],
        command_ids: []
      }
    ] + Samson::Hooks.fire(:stage_permitted_params).flatten
  end
end

app/helpers/stages_helper.rb
# frozen_string_literal: true
module StagesHelper
  def edit_command_link(command)
    admin = current_user.admin? || current_user.admin_for?(command.project)
    edit_url = [:admin, command]
    if command.global?
      title, url =
        if admin
          ["Edit global command", edit_url]
        else
          ["Global command, can only be edited via Admin UI", "#"]
        end
      link_to "", url, title: title, class: "edit-command glyphicon glyphicon-globe no-hover"
    elsif admin
      link_to "", edit_url, title: "Edit in admin UI", class: "edit-command glyphicon glyphicon-edit no-hover"
    end
  end

  def stage_template_icon
    content_tag :span, '',
      class: "glyphicon glyphicon-duplicate",
      title: "Template stage, this stage will be used when copying to new Deploy Groups"
  end
end

app/views/stages/_fields.html.erb
<fieldset>
  <%= form.input :name, required: true %>
  <%= form.input :permalink, required: true if form.object.persisted? %>
  <%= form.input :notify_email_address,
        label: "Notify after deploy",
        help: "Email addresses to notify of finished deploys, separated by <code>;</code>".html_safe
  %>

  <% if DeployGroup.enabled? %>
    <%= render 'deploy_groups/deploy_group_select', form: form %>
  <% else %>
    <%= form.input :production, as: :check_box,
          label: 'Impacts production',
          help: "Deploys to production need to pass a buddy check when BuddyCheck is enabled."
    %>
  <% end %>

  <% help = "Bypass " + [("buddy check" if BuddyCheck.enabled?), "release tracking"].compact.to_sentence %>
  <%= form.input :no_code_deployed, as: :check_box, label: "Does not deploy code", help: help %>

  <%= form.input :run_in_parallel, as: :check_box, label: "Can run in parallel", help: "Deploys are not queued. Executed immediately" %>

  <%= form.input :cancel_queued_deploys, as: :check_box, label: "Max 1 queued deploy per user", help: "When a new deploy is created for a user. Any queued deploys for that user are cancelled. This most useful when trying to not deploy every push for frequently updated projects." %>

  <%= form.input :confirm, as: :check_box, label: "Confirm before deployment", help: "Show a review page before starting a deploy" %>

  <% if @project.releases.any? %>
    <%= form.input :deploy_on_release, as: :check_box, label: "Automatically deploy new releases" %>
  <% end %>

  <% if DeployGroup.enabled? %>
    <%= form.input :is_template, as: :check_box,
          label: "Template Stage",
          help: "This stage can serve as a template to create new stages for its environment (only changing the deploy group)."
    %>
  <% end %>
</fieldset>

<%= render 'shared/commands', form: form %>
<%= render 'shared/dashboard_field', form: form %>

<fieldset>
  <legend>Email on automated deploy failure</legend>
  <div class="col-lg-offset-2">
    <p>When an automated deploy initially fails, send a email to:</p>
  </div>

  <%= form.input :email_committers_on_automated_deploy_failure, as: :check_box, label: "Committers in the diff to last successful deploy" %>

  <div class="col-lg-offset-2">
    <div class="form-group">
      <div class="col-lg-6">
        <p>Addresses (comma separated):</p>
        <%= form.text_field :static_emails_on_automated_deploy_failure, class: "form-control" %>
      </div>
    </div>
  </div>
</fieldset>

<%= Samson::Hooks.render_views(:stage_form, self, form: form) %>

app/views/stages/_form.html.erb
<%= form_for [project, stage], html: { class: "form-horizontal" } do |form| %>
  <%= render 'shared/errors', object: stage %>

  <fieldset>
    <%= render 'stages/fields', form: form %>
  </fieldset>

  <hr>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Save</button>
    </div>
  </div>
<% end %>

app/views/stages/edit.html.erb
<%= breadcrumb @project, @stage, "Edit" %>

<%= page_title "Edit #{@stage.name}" %>

<section>
  <%= render 'form', project: @project, stage: @stage %>
</section>

app/views/stages/index.html.erb
<%= breadcrumb @project, "Stages" %>

<% page_title "#{@project.name} Stages" %>

<section class="tabs">
  <ul id="stages" data-url="<%= reorder_project_stages_path(@project) %>" data-sortable="<%= admin_for_project? %>">
    <% @stages.each.with_index do |stage, index| %>
      <li class="stage-bar bar list-unstyled clearfix<%= ' sortable' if admin_for_project? %>" data-id="stage_id_<%= stage.id %>">
        <%= link_to stage.name, [@project, stage] %>
        <%= resource_lock_icon stage %>
        <%= stage.is_template ? stage_template_icon : '' %>
        <div class="btn-group pull-right">
          <% if admin_for_project? %>
            <%= link_to "Clone", clone_project_stage_path(@project, stage), class: "btn btn-default" %>
          <% end %>
          <%= deploy_link @project, stage %>
        </div>
      </li>
    <% end %>
  </ul>

  <% if admin_for_project? %>
    <%= link_to "Add Stage", new_project_stage_path(@project), class: "btn btn-default" %>
  <% end %>

  <button id="error_message" class="messages btn btn-danger" disabled>
    Failed to save
  </button>

  <button id="success_message" class="messages btn btn-success" disabled>
    Saved
  </button>
</section>

app/views/stages/new.html.erb
<% page_title "New Stage" %>

<%= breadcrumb @project, "New Stage" %>

<section>
  <%= render 'form', project: @project, stage: @stage %>
</section>

app/views/stages/show.html.erb
<% page_title @stage.name %>

<%= breadcrumb @project, @stage %>

<%= render_lock @stage %>

<h1>
  <%= @stage.name %>
  <%= image_tag project_stage_path(@project, @stage, format: :svg, token: Rails.application.config.samson.badge_token), title: "Deploy badge" %>
</h1>

<section>
  <h2>Actions</h2>
  <div>
    <%= deploy_link @project, @stage %>

    <%= render "locks/button", lock: @stage.lock, resource: @stage %>

    <% if admin_for_project? %>
      <%= link_to "Edit", edit_project_stage_path(@project, @stage), class: "btn btn-default" %>
      <%= link_to_delete_button([@project, @stage]) %>
    <% end %>

    <div class="pull-right">
      <%= link_to_history @stage %>
    </div>
  </div>

  <%= render 'shared/dashboard', resource: @stage %>

  <%= Samson::Hooks.render_views(:stage_show, self) %>

  <div id="script-section">
    <h2>Script</h2>
    <pre class="pre-command"><%= "set -ex\n" + @stage.script %></pre>
  </div>

  <% if groups = @stage.deploy_groups.sort_by(&:natural_order).to_a.presence %>
    <h2>Deploy groups</h2>
    <% groups.each do |group| %>
      <%= link_to group.name, group %>
    <% end %>
  <% end %>

  <h2>Recent deploys</h2>
  <table class="table">
    <thead>
      <tr>
        <th>When</th>
        <th>Who</th>
        <% unless @stage %>
          <th>Stage</th>
        <% end %>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "/projects/deploy", collection: @deploys %>
    </tbody>
  </table>
  <%= paginate @deploys %>
</section>